// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PingIt.Api.Data;

#nullable disable

namespace PingIt.Api.Migrations
{
    [DbContext(typeof(PingItDbContext))]
    [Migration("20250528142236_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PingIt.Api.Models.Incident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("HandledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HandledByExternal")
                        .HasColumnType("boolean");

                    b.Property<int?>("HandledByUserId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("numeric");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("HandledByUserId");

                    b.ToTable("Incidents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 6, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 7,
                            Deadline = new DateTime(2025, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "De lantaarnpaal voor huisnummer 12 doet het al dagen niet meer.",
                            HandledByExternal = false,
                            HandledByUserId = 3,
                            Latitude = 51.7501m,
                            Longitude = 5.1305m,
                            Notes = "Ingepland voor reparatie volgende week.",
                            Priority = 2,
                            Status = 1,
                            Title = "Kapotte lantaarnpaal"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 6, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 8,
                            Deadline = new DateTime(2025, 8, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Overal ligt afval op het speelveld achter het winkelcentrum, echt super goor",
                            HandledByExternal = false,
                            HandledByUserId = 3,
                            Latitude = 51.7510m,
                            Longitude = 5.1310m,
                            Notes = "Reinigingsdienst is bezig met opruimen.",
                            Priority = 1,
                            Status = 2,
                            Title = "Zwerfvuil"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 6, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 9,
                            Deadline = new DateTime(2025, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bankje in het parkje bij de kerk is denk ik vernield man. niet spang.",
                            HandledByExternal = false,
                            HandledByUserId = 3,
                            Latitude = 51.7525m,
                            Longitude = 5.1342m,
                            Notes = "Bankje is vervangen.",
                            Priority = 3,
                            Status = 3,
                            Title = "Kapot bankje"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 10,
                            Deadline = new DateTime(2025, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Mijn moeder is bijna gevallen door een losse tegel op de hoek van de Schoolstraat.",
                            HandledByExternal = false,
                            Latitude = 51.7499m,
                            Longitude = 5.1331m,
                            Priority = 2,
                            Status = 0,
                            Title = "Losliggende stoeptegel"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 11,
                            Deadline = new DateTime(2025, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Er ligt een grote boom over het fietspad aan de Buitenkade.",
                            HandledByExternal = false,
                            Latitude = 51.7488m,
                            Longitude = 5.1320m,
                            Priority = 4,
                            Status = 1,
                            Title = "Omgevallen boom"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 6, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 12,
                            Deadline = new DateTime(2025, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "In dat steegje wordt sowieso gedealt. Constant gasten met capuchons op op scooters zijn daar aanwezig 's avonds. Ik vertrouw dit echt niet.",
                            HandledByExternal = false,
                            HandledByUserId = 3,
                            Latitude = 51.7470m,
                            Longitude = 5.1312m,
                            Notes = "Melding doorgestuurd naar politie.",
                            Priority = 3,
                            Status = 2,
                            Title = "Verdacht steegje mogelijke drugshandel"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 6, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 7,
                            Deadline = new DateTime(2025, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Auto staat al dagen op de stoep bij het gemeentehuis.",
                            HandledByExternal = false,
                            HandledByUserId = 3,
                            Latitude = 51.7490m,
                            Longitude = 5.1309m,
                            Notes = "Voertuig is weggesleept.",
                            Priority = 2,
                            Status = 3,
                            Title = "Foutgeparkeerd voertuig"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 6, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deadline = new DateTime(2025, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Na regen staat de straat voor het huis blank, vermoeden is dat deze put het probleem is",
                            HandledByExternal = false,
                            Latitude = 51.7503m,
                            Longitude = 5.1351m,
                            Priority = 3,
                            Status = 0,
                            Title = "Wateroverlast verstopte put"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deadline = new DateTime(2025, 8, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Vliegtuigen vliegen steeds lager over. Ik heb dit ooit al wel eens eerder aangegeven hier is niks mee gedaan!",
                            HandledByExternal = false,
                            Latitude = 51.7518m,
                            Longitude = 5.1306m,
                            Priority = 1,
                            Status = 0,
                            Title = "Geluidsoverlast vliegtuig"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 6, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 13,
                            Deadline = new DateTime(2025, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Die jeugd heeft ook geen respect voor rust he ze zitten de hele avond harde boem boem muziek te draaien en het staat veels te hard in mijn tijd mochten we niet eens naar buiten na 10 uur want dat was gevaarlijk ik weet dat nog goed toen gingen we binnen altijd spelletjes spelen wat een mooie tijden waren dat.",
                            HandledByExternal = false,
                            Latitude = 51.7520m,
                            Longitude = 5.1345m,
                            Priority = 2,
                            Status = 0,
                            Title = "Geluidsoverlast muziek"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 6, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 14,
                            Deadline = new DateTime(2025, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ruit van bushokje bij de Markt is vannacht ingegooid.",
                            HandledByExternal = false,
                            Latitude = 51.7530m,
                            Longitude = 5.1327m,
                            Priority = 4,
                            Status = 1,
                            Title = "Ingegooide bushalte"
                        });
                });

            modelBuilder.Entity("PingIt.Api.Models.IncidentPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IncidentId")
                        .HasColumnType("integer");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId");

                    b.ToTable("IncidentPhotos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IncidentId = 1,
                            PhotoUrl = "/Uploads/kapottelantaarnpaal1.png"
                        },
                        new
                        {
                            Id = 2,
                            IncidentId = 2,
                            PhotoUrl = "/Uploads/zwerfvuil1.png"
                        },
                        new
                        {
                            Id = 3,
                            IncidentId = 2,
                            PhotoUrl = "/Uploads/zwerfvuil2.png"
                        },
                        new
                        {
                            Id = 4,
                            IncidentId = 2,
                            PhotoUrl = "/Uploads/zwerfvuil3.png"
                        },
                        new
                        {
                            Id = 5,
                            IncidentId = 3,
                            PhotoUrl = "/Uploads/kapotbankje1.png"
                        },
                        new
                        {
                            Id = 6,
                            IncidentId = 3,
                            PhotoUrl = "/Uploads/kapotbankje2.png"
                        },
                        new
                        {
                            Id = 7,
                            IncidentId = 4,
                            PhotoUrl = "/Uploads/losliggendestoeptegel1.png"
                        },
                        new
                        {
                            Id = 8,
                            IncidentId = 4,
                            PhotoUrl = "/Uploads/losliggendestoeptegel2.png"
                        },
                        new
                        {
                            Id = 9,
                            IncidentId = 5,
                            PhotoUrl = "/Uploads/omgevallenboom1.png"
                        },
                        new
                        {
                            Id = 10,
                            IncidentId = 6,
                            PhotoUrl = "/Uploads/steegje1.png"
                        },
                        new
                        {
                            Id = 11,
                            IncidentId = 7,
                            PhotoUrl = "/Uploads/foutgeparkeerd1.png"
                        },
                        new
                        {
                            Id = 12,
                            IncidentId = 7,
                            PhotoUrl = "/Uploads/foutgeparkeerd2.png"
                        },
                        new
                        {
                            Id = 13,
                            IncidentId = 8,
                            PhotoUrl = "/Uploads/verstopteput1.png"
                        },
                        new
                        {
                            Id = 14,
                            IncidentId = 8,
                            PhotoUrl = "/Uploads/verstopteput2.png"
                        },
                        new
                        {
                            Id = 15,
                            IncidentId = 11,
                            PhotoUrl = "/Uploads/bushokje1.png"
                        },
                        new
                        {
                            Id = 16,
                            IncidentId = 11,
                            PhotoUrl = "/Uploads/bushokje2.png"
                        });
                });

            modelBuilder.Entity("PingIt.Api.Models.IncidentStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ChangedByUserId")
                        .HasColumnType("integer");

                    b.Property<int>("IncidentId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("IncidentId");

                    b.ToTable("IncidentStatusHistories");
                });

            modelBuilder.Entity("PingIt.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("WantsNotifications")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Wijk en Aalburg",
                            Email = "admin@pingit.nl",
                            FirstName = "Piet",
                            HouseNumber = "11",
                            LastName = "De Vries",
                            PasswordHash = "e8oCXv9PuHe+qG+qxWyQm2XJet+6I7fB+2uXctNLQg4=",
                            PhoneNumber = "06-12345678",
                            PostalCode = "4261AA",
                            Role = 2,
                            Street = "Dorpsstraat",
                            WantsNotifications = false
                        },
                        new
                        {
                            Id = 2,
                            City = "Wijk en Aalburg",
                            Email = "klaas.bakker@wijkmail.nl",
                            FirstName = "Klaas",
                            HouseNumber = "12",
                            LastName = "Bakker",
                            PasswordHash = "e8oCXv9PuHe+qG+qxWyQm2XJet+6I7fB+2uXctNLQg4=",
                            PhoneNumber = "06-12345678",
                            PostalCode = "4261AA",
                            Role = 2,
                            Street = "Dorpsstraat",
                            WantsNotifications = true
                        },
                        new
                        {
                            Id = 3,
                            City = "Wijk en Aalburg",
                            Email = "worker@pingit.nl",
                            FirstName = "Henk",
                            HouseNumber = "13",
                            LastName = "Van Dijk",
                            PasswordHash = "e8oCXv9PuHe+qG+qxWyQm2XJet+6I7fB+2uXctNLQg4=",
                            PhoneNumber = "06-12345678",
                            PostalCode = "4261AA",
                            Role = 1,
                            Street = "Dorpsstraat",
                            WantsNotifications = false
                        },
                        new
                        {
                            Id = 4,
                            City = "Wijk en Aalburg",
                            Email = "gerda.smit@wijkmail.nl",
                            FirstName = "Gerda",
                            HouseNumber = "14",
                            LastName = "Smit",
                            PasswordHash = "e8oCXv9PuHe+qG+qxWyQm2XJet+6I7fB+2uXctNLQg4=",
                            PhoneNumber = "06-12345678",
                            PostalCode = "4261AA",
                            Role = 1,
                            Street = "Dorpsstraat",
                            WantsNotifications = true
                        },
                        new
                        {
                            Id = 5,
                            City = "Wijk en Aalburg",
                            Email = "lisa.koster@wijkmail.nl",
                            FirstName = "Lisa",
                            HouseNumber = "15",
                            LastName = "Koster",
                            PasswordHash = "e8oCXv9PuHe+qG+qxWyQm2XJet+6I7fB+2uXctNLQg4=",
                            PhoneNumber = "06-12345678",
                            PostalCode = "4261AA",
                            Role = 1,
                            Street = "Dorpsstraat",
                            WantsNotifications = false
                        },
                        new
                        {
                            Id = 6,
                            City = "Wijk en Aalburg",
                            Email = "thomas.de boer@wijkmail.nl",
                            FirstName = "Thomas",
                            HouseNumber = "16",
                            LastName = "De Boer",
                            PasswordHash = "e8oCXv9PuHe+qG+qxWyQm2XJet+6I7fB+2uXctNLQg4=",
                            PhoneNumber = "06-12345678",
                            PostalCode = "4261AA",
                            Role = 1,
                            Street = "Dorpsstraat",
                            WantsNotifications = true
                        },
                        new
                        {
                            Id = 7,
                            City = "Wijk en Aalburg",
                            Email = "sanne.vos@wijkmail.nl",
                            FirstName = "Sanne",
                            HouseNumber = "17",
                            LastName = "Vos",
                            PasswordHash = "e8oCXv9PuHe+qG+qxWyQm2XJet+6I7fB+2uXctNLQg4=",
                            PhoneNumber = "06-12345678",
                            PostalCode = "4261AA",
                            Role = 0,
                            Street = "Dorpsstraat",
                            WantsNotifications = false
                        },
                        new
                        {
                            Id = 8,
                            City = "Wijk en Aalburg",
                            Email = "bram.meijer@wijkmail.nl",
                            FirstName = "Bram",
                            HouseNumber = "18",
                            LastName = "Meijer",
                            PasswordHash = "e8oCXv9PuHe+qG+qxWyQm2XJet+6I7fB+2uXctNLQg4=",
                            PhoneNumber = "06-12345678",
                            PostalCode = "4261AA",
                            Role = 0,
                            Street = "Dorpsstraat",
                            WantsNotifications = true
                        },
                        new
                        {
                            Id = 9,
                            City = "Wijk en Aalburg",
                            Email = "eva.mulder@wijkmail.nl",
                            FirstName = "Eva",
                            HouseNumber = "19",
                            LastName = "Mulder",
                            PasswordHash = "e8oCXv9PuHe+qG+qxWyQm2XJet+6I7fB+2uXctNLQg4=",
                            PhoneNumber = "06-12345678",
                            PostalCode = "4261AA",
                            Role = 0,
                            Street = "Dorpsstraat",
                            WantsNotifications = false
                        },
                        new
                        {
                            Id = 10,
                            City = "Wijk en Aalburg",
                            Email = "mark.jansen@wijkmail.nl",
                            FirstName = "Mark",
                            HouseNumber = "20",
                            LastName = "Jansen",
                            PasswordHash = "e8oCXv9PuHe+qG+qxWyQm2XJet+6I7fB+2uXctNLQg4=",
                            PhoneNumber = "06-12345678",
                            PostalCode = "4261AA",
                            Role = 0,
                            Street = "Dorpsstraat",
                            WantsNotifications = true
                        },
                        new
                        {
                            Id = 11,
                            City = "Wijk en Aalburg",
                            Email = "inge.de vries@wijkmail.nl",
                            FirstName = "Inge",
                            HouseNumber = "21",
                            LastName = "De Vries",
                            PasswordHash = "e8oCXv9PuHe+qG+qxWyQm2XJet+6I7fB+2uXctNLQg4=",
                            PhoneNumber = "06-12345678",
                            PostalCode = "4261AA",
                            Role = 0,
                            Street = "Dorpsstraat",
                            WantsNotifications = false
                        },
                        new
                        {
                            Id = 12,
                            City = "Wijk en Aalburg",
                            Email = "daan.bakker@wijkmail.nl",
                            FirstName = "Daan",
                            HouseNumber = "22",
                            LastName = "Bakker",
                            PasswordHash = "e8oCXv9PuHe+qG+qxWyQm2XJet+6I7fB+2uXctNLQg4=",
                            PhoneNumber = "06-12345678",
                            PostalCode = "4261AA",
                            Role = 0,
                            Street = "Dorpsstraat",
                            WantsNotifications = true
                        },
                        new
                        {
                            Id = 13,
                            City = "Wijk en Aalburg",
                            Email = "julia.van dijk@wijkmail.nl",
                            FirstName = "Julia",
                            HouseNumber = "23",
                            LastName = "Van Dijk",
                            PasswordHash = "e8oCXv9PuHe+qG+qxWyQm2XJet+6I7fB+2uXctNLQg4=",
                            PhoneNumber = "06-12345678",
                            PostalCode = "4261AA",
                            Role = 0,
                            Street = "Dorpsstraat",
                            WantsNotifications = false
                        },
                        new
                        {
                            Id = 14,
                            City = "Wijk en Aalburg",
                            Email = "willem.smit@wijkmail.nl",
                            FirstName = "Willem",
                            HouseNumber = "24",
                            LastName = "Smit",
                            PasswordHash = "e8oCXv9PuHe+qG+qxWyQm2XJet+6I7fB+2uXctNLQg4=",
                            PhoneNumber = "06-12345678",
                            PostalCode = "4261AA",
                            Role = 0,
                            Street = "Dorpsstraat",
                            WantsNotifications = true
                        },
                        new
                        {
                            Id = 15,
                            City = "Wijk en Aalburg",
                            Email = "fleur.koster@wijkmail.nl",
                            FirstName = "Fleur",
                            HouseNumber = "25",
                            LastName = "Koster",
                            PasswordHash = "e8oCXv9PuHe+qG+qxWyQm2XJet+6I7fB+2uXctNLQg4=",
                            PhoneNumber = "06-12345678",
                            PostalCode = "4261AA",
                            Role = 0,
                            Street = "Dorpsstraat",
                            WantsNotifications = false
                        },
                        new
                        {
                            Id = 16,
                            City = "Wijk en Aalburg",
                            Email = "jan.de boer@wijkmail.nl",
                            FirstName = "Jan",
                            HouseNumber = "26",
                            LastName = "De Boer",
                            PasswordHash = "e8oCXv9PuHe+qG+qxWyQm2XJet+6I7fB+2uXctNLQg4=",
                            PhoneNumber = "06-12345678",
                            PostalCode = "4261AA",
                            Role = 0,
                            Street = "Dorpsstraat",
                            WantsNotifications = true
                        });
                });

            modelBuilder.Entity("PingIt.Api.Models.Incident", b =>
                {
                    b.HasOne("PingIt.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PingIt.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("HandledByUserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("PingIt.Api.Models.IncidentPhoto", b =>
                {
                    b.HasOne("PingIt.Api.Models.Incident", null)
                        .WithMany("Photos")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PingIt.Api.Models.IncidentStatusHistory", b =>
                {
                    b.HasOne("PingIt.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PingIt.Api.Models.Incident", null)
                        .WithMany()
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PingIt.Api.Models.Incident", b =>
                {
                    b.Navigation("Photos");
                });
#pragma warning restore 612, 618
        }
    }
}
